/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.contentTypes = {
    attach: function attach(context) {

      var $context = $(context);
      $context.find('.views-menu-extra-condition').each(function () {
        $(this).drupalSetSummary(function (context) {
          var vals = [];
          $(context).find('input:checked').next('label').each(function () {
            vals.push(Drupal.checkPlain($(this).text()));
          });
          $(context).find('input:text').each(function () {
            vals.push(Drupal.checkPlain($(this).val()));
          });
          $(context).find('textarea').each(function () {
            vals.push(Drupal.checkPlain($(this).val()));
          });
          $(context).find('select:selected').each(function () {
            vals.push(Drupal.checkPlain($(this).val()));
          });

          return vals.join(', ');
        });
      });
    }
  };
})(jQuery, Drupal);
